apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-tier
  labels:
    app: expenditure
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenditure
      tier: backend
  template:
    metadata:
      labels:
        app: expenditure
        tier: backend
    spec:
      containers:
      - name: backend
        image: docker.io/mssanjay84/expenditure-backend:v1
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-service"
