apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenditure
      tier: frontend
  template:
    metadata:
      labels:
        app: expenditure
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/mssanjay84/expenditure-frontend:v1
        ports:
        - containerPort: 8080
