apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deploy.yaml
- frontend-svc.yaml
- backend-deploy.yaml
- backend-svc.yaml
- postgres-deploy.yaml
- postgres-svc.yaml
- rabbitmq-deploy.yaml
- rabbitmq-svc.yaml
- network-policies.yaml

images:
- name: expenditure-frontend:latest
  newName: docker.io/mssanjay84/expenditure-frontend
  newTag: v1
- name: expenditure-backend:latest
  newName: docker.io/mssanjay84/expenditure-backend
  newTag: v1
