apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-tier
  labels:
    app: expenditure
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenditure
      tier: database
  template:
    metadata:
      labels:
        app: expenditure
        tier: database
    spec:
      containers:
      - name: postgres
        image: docker.io/library/postgresq:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: "bank_admin"
        - name: POSTGRESQL_PASSWORD
          value: "InitialDummyPasswordToOverrideWithVault"
        - name: POSTGRESQL_DATABASE
          value: "expenditure_db"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
